### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'bandCount'

### ISSUE THREAD

**Issue by EASC** [semiautomaticgit/SemiAutomaticClassificationPlugin#105]
Hello, I have a  problem when I try to load a multiband image.

When I install SemiAutomaticClassification Plugin, there are some warnings detailed in
[scp_warnings.txt](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/files/4500534/scp_warnings.txt)

When I try to load a multiband image, next error comes out:

2020-04-19T19:18:46 WARNING Traceback (most recent call last):
File "/home/andres/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/bandsetTab.py", line 377, in rasterLayerName
cfg.bst.rasterToBandName(imgNm)
File "/home/andres/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/maininterface/bandsetTab.py", line 1027, in rasterToBandName
b = r.bandCount()
AttributeError: 'NoneType' object has no attribute 'bandCount'

I'm working on Ubuntu 18.04
QGIS 3.10
pip version 9.0.1
Python 3.6.9

Could it be a bug in SCP plugin?
Thank you for your help.

**Comment by semiautomaticgit** [comment]
Hello, it seems an installation issue.
Please copy the log file https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error

**Comment by WhiteCarcosa** [comment]
Same issue. Fresh install does not fix.

**Comment by semiautomaticgit** [comment]
I'm closing this because of the new version 7.
If you still get the same issue, please reopen it
